spring.application.name=restaurant

server.port=${PORT:8080}

spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS}
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=60s

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

spring.elasticsearch.repositories.enabled=false
spring.data.elasticsearch.auto-index-creation=false
spring.elasticsearch.rest.compatibility-mode=true

spring.elasticsearch.username=${SPRING_ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${SPRING_ELASTICSEARCH_PASSWORD}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
