spring.application.name=restaurant

spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS}
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=60s

https://keycloak-production-fd8d.up.railway.app/realms/restaurant-review
